
import argparse

parser = argparse.ArgumentParser(
    description='Module to analyse the quality of the topographic maps generated by SpiNNaker')
parser.add_argument('path', help='path of .npz archive', nargs='*')
parser.add_argument('-o', '--output', type=str,
                    help="name of the numpy archive storing simulation results",
                    dest='filename')
parser.add_argument('--plot', help="display plots",
                    action="store_true")

parser.add_argument('--snapshots', help="run snapshot analysis",
                    action="store_true")

args = parser.parse_args()
