
import argparse

parser = argparse.ArgumentParser(
    description='Module to analyse the quality of the topographic maps '
                'generated by SpiNNaker')
flags = parser.add_argument_group('flag arguments')
parser.add_argument('path', help='path of .npz archive', nargs='*')
parser.add_argument('-o', '--output', type=str,
                    help="name of the numpy archive storing simulation results",
                    dest='filename')
flags.add_argument('--plot', help="display plots",
                    action="store_true")

flags.add_argument('--snapshots', help="run snapshot analysis",
                    action="store_true")

# flag to force re-analysis
flags.add_argument('--no-cache', help="force simulation re-analysis without "
                                       "using cached information",
                    action="store_true", dest="no_cache")

args = parser.parse_args()
